# This file was generated by GoReleaser. DO NOT EDIT.
class Topframe < Formula
    desc "Local webpage screen overlay for customizing your computing experience"
    homepage "https://github.com/progrium/topframe"
    version "0.2.0"
  
    if OS.mac?
        url "https://github.com/progrium/topframe/releases/download/v0.2.0/topframe_0.2.0.zip"
        sha256 "765c35729e1523908e51d0582c50cc5728ec068dbf5bf8397264364ba8b9858a"
    elsif OS.linux?
    end
  
    def install
        bin.install "topframe"
    end
end
